controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_lucky_number:
    path: /invoice/{invoiceId}
    controller: App\Controller\InvoiceController::invoice
